### ISSUE TITLE
mypersonalproject

### ISSUE THREAD

**Issue by Shahnawaz12345-678910** [Shahnawaz12345-678910/linux-tasks-#1]
###  Repository Structure

```
├── docker/
│   ├── Dockerfile
│   └── docker-compose.yml
├── k8s/
│   ├── rails-deployment.yaml
│   ├── rails-service.yaml
│   ├── postgres-statefulset.yaml
│   ├── postgres-service.yaml
│   ├── ingress.yaml
├── argocd/
│   ├── application.yaml
│   ├── argocd-cm.yaml
│   ├── argocd-rbac-cm.yaml
│   └── repo-secret.yaml
├── tekton/
│   ├── pipeline.yaml
│   ├── tasks/
│   │   ├── git-clone.yaml
│   │   └── kaniko.yaml
│   └── pipeline-run.yaml
├── manifests/
│   └── namespace.yaml
└── README.md
```

---

### 📦 docker/Dockerfile
```dockerfile
FROM ruby:3.2
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
WORKDIR /app
COPY Gemfile* ./
RUN bundle install
COPY . .
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
```

---

### 📦 docker/docker-compose.yml
```yaml
version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: password
volumes:
  pg_data:
```

---

### ☸️ k8s/postgres-statefulset.yaml
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

---

### ☸️ k8s/postgres-service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: postgres
```

---

### ☸️ k8s/rails-deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: <your-dockerhub-username>/rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PASSWORD
          value: password
```

---

### ☸️ k8s/rails-service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
```

---

### ☸️ k8s/ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rails.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rails-service
            port:
              number: 80
```

---

### 🚀 argocd/application.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-username/your-private-repo.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
```

---

### 🔧 tekton/pipeline.yaml
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-ci
spec:
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    params:
      - name: url
        value: https://github.com/<your-fork>/rails-app.git
  - name: kaniko-build
    runAfter:
      - clone
    taskRef:
      name: kaniko
    params:
      - name: IMAGE
        value: docker.io/<your-username>/rails-app:latest
```

---

###  tekton/pipeline-run.yaml
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: rails-ci-run
spec:
  pipelineRef:
    name: rails-ci
  workspaces:
    - name: shared-data
      emptyDir: {}
